### ISSUE TITLE
The prebuilt packages download link is dead

### ISSUE THREAD

**Issue by Jpe230** [CrealityTech/sonic_pad_os#1]
As mentioned in the title, the download link times out, an alternative server, gdrive or uploading them to this repository would be helpful.

**Comment by rmcolbert** [comment]
I'm currently searching for the packages used in the toolchain and opening additional issues for them w/ options for fixing the ones that aren't accessible via the original source.

**Comment by Jpe230** [comment]
Seems like the packages are now available, closing this issue.
